export const OptionCities = [
  { value: "acehbarat", label: "Aceh Barat" },
  { value: "acehbaratdaya", label: "Aceh Barat Daya" },
  { value: "acehbesar", label: "Aceh Besar" },
  { value: "acehjaya", label: "Aceh Jaya" },
  { value: "acehselatan", label: "Aceh Selatan" },
  { value: "acehsingkil", label: "Aceh Singkil" },
  { value: "acehtamiang", label: "Aceh Tamiang" },
  { value: "acehtengah", label: "Aceh Tengah" },
  { value: "acehtenggara", label: "Aceh Tenggara" },
  { value: "acehtimur", label: "Aceh Timur" },
  { value: "acehutara", label: "Aceh Utara" },
  { value: "agam", label: "Agam" },
  { value: "alor", label: "Alor" },
  { value: "ambarawa", label: "Ambarawa" },
  { value: "ambon", label: "Ambon" },
  { value: "amlapura", label: "Amlapura" },
  { value: "amuntai", label: "Amuntai" },
  { value: "argamakmur", label: "Arga Makmur" },
  { value: "asahan", label: "Asahan" },
  { value: "asmat", label: "Asmat" },
  { value: "atambua", label: "Atambua" },
  { value: "babo", label: "Babo" },
  { value: "badung", label: "Badung" },
  { value: "bagansiapiapi", label: "Bagansiapiapi" },
  { value: "bahaurkalteng", label: "Bahaur Kalteng" },
  { value: "bajawa", label: "Bajawa" },
  { value: "balangan", label: "Balangan" },
  { value: "balige", label: "Balige" },
  { value: "balikpapan", label: "Balikpapan" },
  { value: "bandaaceh", label: "Banda Aceh" },
  { value: "bandarlampung", label: "Bandar Lampung" },
  { value: "bandung", label: "Bandung" },
  { value: "bandungbarat", label: "Bandung Barat" },
  { value: "banggai", label: "Banggai" },
  { value: "banggaikepulauan", label: "Banggai Kepulauan" },
  { value: "banggailaut", label: "Banggai Laut" },
  { value: "bangka", label: "Bangka" },
  { value: "bangkabarat", label: "Bangka Barat" },
  { value: "bangkaselatan", label: "Bangka Selatan" },
  { value: "bangkatengah", label: "Bangka Tengah" },
  { value: "bangkalan", label: "Bangkalan" },
  { value: "bangkinang", label: "Bangkinang" },
  { value: "bangko", label: "Bangko" },
  { value: "bangli", label: "Bangli" },
  { value: "banjar", label: "Banjar" },
  { value: "banjarbaru", label: "Banjarbaru" },
  { value: "banjarmasin", label: "Banjarmasin" },
  { value: "banjarnegara", label: "Banjarnegara" },
  { value: "bantaeng", label: "Bantaeng" },
  { value: "banten", label: "Banten" },
  { value: "bantul", label: "Bantul" },
  { value: "banyuasin", label: "Banyuasin" },
  { value: "banyumas", label: "Banyumas" },
  { value: "banyuwangi", label: "Banyuwangi" },
  { value: "barabai", label: "Barabai" },
  { value: "barito", label: "Barito" },
  { value: "baritokuala", label: "Barito Kuala" },
  { value: "baritoselatan", label: "Barito Selatan" },
  { value: "baritotimur", label: "Barito Timur" },
  { value: "baritoutara", label: "Barito Utara" },
  { value: "barru", label: "Barru" },
  { value: "batam", label: "Batam" },
  { value: "batang", label: "Batang" },
  { value: "batanghari", label: "Batang Hari" },
  { value: "batu", label: "Batu" },
  { value: "batubara", label: "Batu Bara" },
  { value: "baturaja", label: "Baturaja" },
  { value: "batusangkar", label: "Batusangkar" },
  { value: "baubau", label: "Baubau" },
  { value: "bekasi", label: "Bekasi" },
  { value: "belitung", label: "Belitung" },
  { value: "belitungtimur", label: "Belitung Timur" },
  { value: "belu", label: "Belu" },
  { value: "benermeriah", label: "Bener Meriah" },
  { value: "bengkalis", label: "Bengkalis" },
  { value: "bengkayang", label: "Bengkayang" },
  { value: "bengkulu", label: "Bengkulu" },
  { value: "bengkuluselatan", label: "Bengkulu Selatan" },
  { value: "bengkulutengah", label: "Bengkulu Tengah" },
  { value: "bengkuluutara", label: "Bengkulu Utara" },
  { value: "benteng", label: "Benteng" },
  { value: "berau", label: "Berau" },
  { value: "biak", label: "Biak" },
  { value: "biaknumfor", label: "Biak Numfor" },
  { value: "bima", label: "Bima" },
  { value: "binjai", label: "Binjai" },
  { value: "bintan", label: "Bintan" },
  { value: "bireuen", label: "Bireuen" },
  { value: "bitung", label: "Bitung" },
  { value: "blitar", label: "Blitar" },
  { value: "blora", label: "Blora" },
  { value: "boalemo", label: "Boalemo" },
  { value: "bogor", label: "Bogor" },
  { value: "bojonegoro", label: "Bojonegoro" },
  { value: "bolaangmongondow", label: "Bolaang Mongondow" },
  { value: "bolaangmongondowselatan", label: "Bolaang Mongondow Selatan" },
  { value: "bolaangmongondowtimur", label: "Bolaang Mongondow Timur" },
  { value: "bolaangmongondowutara", label: "Bolaang Mongondow Utara" },
  { value: "bombana", label: "Bombana" },
  { value: "bondowoso", label: "Bondowoso" },
  { value: "bone", label: "Bone" },
  { value: "bonebolango", label: "Bone Bolango" },
  { value: "bontang", label: "Bontang" },
  { value: "bovendigoel", label: "Boven Digoel" },
  { value: "boyolali", label: "Boyolali" },
  { value: "brebes", label: "Brebes" },
  { value: "bukittinggi", label: "Bukittinggi" },
  { value: "bulasbtmaluku", label: "Bula SBT Maluku" },
  { value: "buleleng", label: "Buleleng" },
  { value: "bulukumba", label: "Bulukumba" },
  { value: "bulungan", label: "Bulungan" },
  { value: "bungo", label: "Bungo" },
  { value: "buntok", label: "Buntok" },
  { value: "buol", label: "Buol" },
  { value: "buru", label: "Buru" },
  { value: "buruselatan", label: "Buru Selatan" },
  { value: "buton", label: "Buton" },
  { value: "butonutara", label: "Buton Utara" },
  { value: "cianjur", label: "Cianjur" },
  { value: "cilacap", label: "Cilacap" },
  { value: "cilegon", label: "Cilegon" },
  { value: "cimahi", label: "Cimahi" },
  { value: "cirebon", label: "Cirebon" },
  { value: "dairi", label: "Dairi" },
  { value: "dejavu", label: "Dejavu" },
  { value: "deliserdang", label: "Deli Serdang" },
  { value: "demak", label: "Demak" },
  { value: "denpasar", label: "Denpasar" },
  { value: "depok", label: "Depok" },
  { value: "dharmasraya", label: "Dharmasraya" },
  { value: "dompu", label: "Dompu" },
  { value: "donggala", label: "Donggala" },
  { value: "dumai", label: "Dumai" },
  { value: "empatenam", label: "Empat Lawang" },
  { value: "ende", label: "Ende" },
  { value: "enrekang", label: "Enrekang" },
  { value: "fakfak", label: "Fakfak" },
  { value: "flores", label: "Flores" },
  { value: "gianyar", label: "Gianyar" },
  { value: "gorontalo", label: "Gorontalo" },
  { value: "gowa", label: "Gowa" },
  { value: "gresik", label: "Gresik" },
  { value: "gunungsitoli", label: "Gunung Sitoli" },
  { value: "gunungkidul", label: "Gunungkidul" },
  { value: "halmahera", label: "Halmahera" },
  { value: "halsel", label: "Halmahera Selatan" },
  { value: "haryojati", label: "Haryojati" },
  { value: "indramayu", label: "Indramayu" },
  { value: "jakarta", label: "Jakarta" },
  { value: "jambi", label: "Jambi" },
  { value: "jepara", label: "Jepara" },
  { value: "jember", label: "Jember" },
  { value: "jombang", label: "Jombang" },
  { value: "kabupatenbatubara", label: "Kabupaten Batu Bara" },
  { value: "kabupatentangerang", label: "Kabupaten Tangerang" },
  { value: "kebumen", label: "Kebumen" },
  { value: "kediri", label: "Kediri" },
  { value: "kefamenanu", label: "Kefamenanu" },
  { value: "kendal", label: "Kendal" },
  { value: "kendari", label: "Kendari" },
  { value: "kepanjen", label: "Kepanjen" },
  { value: "kepmeranti", label: "Kepulauan Meranti" },
  { value: "ketapang", label: "Ketapang" },
  { value: "klaten", label: "Klaten" },
  { value: "klungkung", label: "Klungkung" },
  { value: "koba", label: "Koba" },
  { value: "kolaka", label: "Kolaka" },
  { value: "kolakatimur", label: "Kolaka Timur" },
  { value: "kolakautara", label: "Kolaka Utara" },
  { value: "komodo", label: "Komodo" },
  { value: "kotaagung", label: "Kota Agung" },
  { value: "kotabumi", label: "Kotabumi" },
  { value: "kotabaru", label: "Kotabaru" },
  { value: "kotamobagu", label: "Kotamobagu" },
  { value: "kudus", label: "Kudus" },
  { value: "kulonprogo", label: "Kulon Progo" },
  { value: "kuningan", label: "Kuningan" },
  { value: "kupang", label: "Kupang" },
  { value: "kutai", label: "Kutai" },
  { value: "kutaiimur", label: "Kutai Timur" },
  { value: "kutara", label: "Kutai Utara" },
  { value: "lamandau", label: "Lamandau" },
  { value: "lamongan", label: "Lamongan" },
  { value: "lampungbarat", label: "Lampung Barat" },
  { value: "lampungselatan", label: "Lampung Selatan" },
  { value: "lampungtengah", label: "Lampung Tengah" },
  { value: "lampungtimur", label: "Lampung Timur" },
  { value: "lampungutara", label: "Lampung Utara" },
  { value: "landak", label: "Landak" },
  { value: "langkat", label: "Langkat" },
  { value: "langsa", label: "Langsa" },
  { value: "leba", label: "Leba" },
  { value: "lebak", label: "Lebak" },
  { value: "legi", label: "Legi" },
  { value: "lombok", label: "Lombok" },
  { value: "lubuklinggau", label: "Lubuklinggau" },
  { value: "lumajang", label: "Lumajang" },
  { value: "luwu", label: "Luwu" },
  { value: "luwutimur", label: "Luwu Timur" },
  { value: "luwuutara", label: "Luwu Utara" },
  { value: "mada", label: "Mada" },
  { value: "magelang", label: "Magelang" },
  { value: "madiun", label: "Madiun" },
  { value: "magetan", label: "Magetan" },
  { value: "majene", label: "Majene" },
  { value: "majalengka", label: "Majalengka" },
  { value: "makassar", label: "Makassar" },
  { value: "malang", label: "Malang" },
  { value: "malaka", label: "Malaka" },
  { value: "malinau", label: "Malinau" },
  { value: "mamasa", label: "Mamasa" },
  { value: "mamberamo", label: "Mamberamo" },
  { value: "manado", label: "Manado" },
  { value: "manokwari", label: "Manokwari" },
  { value: "marabahan", label: "Marabahan" },
  { value: "maros", label: "Maros" },
  { value: "mataram", label: "Mataram" },
  { value: "maybrat", label: "Maybrat" },
  { value: "medan", label: "Medan" },
  { value: "melawi", label: "Melawi" },
  { value: "mentawai", label: "Mentawai" },
  { value: "merangin", label: "Merangin" },
  { value: "merauke", label: "Merauke" },
  { value: "mesuji", label: "Mesuji" },
  { value: "metro", label: "Metro" },
  { value: "mimika", label: "Mimika" },
  { value: "minahasa", label: "Minahasa" },
  { value: "minahasaselatan", label: "Minahasa Selatan" },
  { value: "minahasatenggara", label: "Minahasa Tenggara" },
  { value: "minahasutara", label: "Minahasa Utara" },
  { value: "mojokerto", label: "Mojokerto" },
  { value: "morowali", label: "Morowali" },
  { value: "morowaliutara", label: "Morowali Utara" },
  { value: "muarabungo", label: "Muara Bungo" },
  { value: "muaraenim", label: "Muara Enim" },
  { value: "muaratebo", label: "Muara Tebo" },
  { value: "muarosijunjung", label: "Muaro Sijunjung" },
  { value: "musi", label: "Musi" },
  { value: "musi-banyuasin", label: "Musi Banyuasin" },
  { value: "nabire", label: "Nabire" },
  { value: "naganraya", label: "Nagan Raya" },
  { value: "natal", label: "Natal" },
  { value: "naganraya", label: "Nagan Raya" },
  { value: "nias", label: "Nias" },
  { value: "ngawi", label: "Ngawi" },
  { value: "nganjuk", label: "Nganjuk" },
  { value: "ntb", label: "NTB" },
  { value: "ntt", label: "NTT" },
  { value: "pacitan", label: "Pacitan" },
  { value: "padang", label: "Padang" },
  { value: "padangsidempuan", label: "Padangsidempuan" },
  { value: "pagaralam", label: "Pagar Alam" },
  { value: "painan", label: "Painan" },
  { value: "palangka", label: "Palangka" },
  { value: "palembang", label: "Palembang" },
  { value: "palopo", label: "Palopo" },
  { value: "palu", label: "Palu" },
  { value: "pamekasan", label: "Pamekasan" },
  { value: "pandeglang", label: "Pandeglang" },
  { value: "pangkalanbun", label: "Pangkalan Bun" },
  { value: "pangkalpinang", label: "Pangkalpinang" },
  { value: "parepare", label: "Parepare" },
  { value: "pariaman", label: "Pariaman" },
  { value: "pasuruan", label: "Pasuruan" },
  { value: "pati", label: "Pati" },
  { value: "payakumbuh", label: "Payakumbuh" },
  { value: "pekalongan", label: "Pekalongan" },
  { value: "pekanbaru", label: "Pekanbaru" },
  { value: "pemalang", label: "Pemalang" },
  { value: "pematangsiantar", label: "Pematang Siantar" },
  { value: "pendopo", label: "Pendopo" },
  { value: "pinrang", label: "Pinrang" },
  { value: "pleihari", label: "Plei Hari" },
  { value: "polewali", label: "Polewali" },
  { value: "ponorogo", label: "Ponorogo" },
  { value: "pontianak", label: "Pontianak" },
  { value: "poso", label: "Poso" },
  { value: "prabumulih", label: "Prabumulih" },
  { value: "praya", label: "Praya" },
  { value: "probolinggo", label: "Probolinggo" },
  { value: "purbalingga", label: "Purbalingga" },
  { value: "purwakarta", label: "Purwakarta" },
  { value: "purwokerto", label: "Purwokerto" },
  { value: "putussibau", label: "Putussibau" },
  { value: "raha", label: "Raha" },
  { value: "rangkasbitung", label: "Rangkasbitung" },
  { value: "rantau", label: "Rantau" },
  { value: "rantauprapat", label: "Rantauprapat" },
  { value: "rantepao", label: "Rantepao" },
  { value: "rembang", label: "Rembang" },
  { value: "rengat", label: "Rengat" },
  { value: "ruteng", label: "Ruteng" },
  { value: "sabang", label: "Sabang" },
  { value: "salatiga", label: "Salatiga" },
  { value: "samarinda", label: "Samarinda" },
  { value: "sampang", label: "Sampang" },
  { value: "sampit", label: "Sampit" },
  { value: "sanggau", label: "Sanggau" },
  { value: "sawahlunto", label: "Sawahlunto" },
  { value: "sekayu", label: "Sekayu" },
  { value: "selong", label: "Selong" },
  { value: "semarang", label: "Semarang" },
  { value: "sengkang", label: "Sengkang" },
  { value: "serang", label: "Serang" },
  { value: "serui", label: "Serui" },
  { value: "sibolga", label: "Sibolga" },
  { value: "sidikalang", label: "Sidikalang" },
  { value: "sidoarjo", label: "Sidoarjo" },
  { value: "sigli", label: "Sigli" },
  { value: "singaraja", label: "Singaraja" },
  { value: "singkawang", label: "Singkawang" },
  { value: "sinjai", label: "Sinjai" },
  { value: "sintang", label: "Sintang" },
  { value: "situbondo", label: "Situbondo" },
  { value: "slawi", label: "Slawi" },
  { value: "sleman", label: "Sleman" },
  { value: "soasiu", label: "Soasiu" },
  { value: "soe", label: "Soe" },
  { value: "solo", label: "Solo" },
  { value: "solok", label: "Solok" },
  { value: "soreang", label: "Soreang" },
  { value: "sorong", label: "Sorong" },
  { value: "sragen", label: "Sragen" },
  { value: "subang", label: "Subang" },
  { value: "sukabumi", label: "Sukabumi" },
  { value: "sukoharjo", label: "Sukoharjo" },
  { value: "sumedang", label: "Sumedang" },
  { value: "sumenep", label: "Sumenep" },
  { value: "sungailiat", label: "Sungailiat" },
  { value: "sungaipenuh", label: "Sungai Penuh" },
  { value: "sungguminasa", label: "Sungguminasa" },
  { value: "surabaya", label: "Surabaya" },
  { value: "surakarta", label: "Surakarta" },
  { value: "tabanan", label: "Tabanan" },
  { value: "tahuna", label: "Tahuna" },
  { value: "takalar", label: "Takalar" },
  { value: "takengon", label: "Takengon" },
  { value: "tamianglayang", label: "Tamiang Layang" },
  { value: "tanahgrogot", label: "Tanah Grogot" },
  { value: "tangerang", label: "Tangerang" },
  { value: "tanjungbalai", label: "Tanjung Balai" },
  { value: "tanjungenim", label: "Tanjung Enim" },
  { value: "tanjungpandan", label: "Tanjung Pandan" },
  { value: "tanjungpinang", label: "Tanjung Pinang" },
  { value: "tanjungredep", label: "Tanjung Redep" },
  { value: "tapaktuan", label: "Tapaktuan" },
  { value: "tarakan", label: "Tarakan" },
  { value: "tarutung", label: "Tarutung" },
  { value: "tasikmalaya", label: "Tasikmalaya" },
  { value: "tegal", label: "Tegal" },
  { value: "temanggung", label: "Temanggung" },
  { value: "tembilahan", label: "Tembilahan" },
  { value: "tenggarong", label: "Tenggarong" },
  { value: "ternate", label: "Ternate" },
  { value: "tolitoli", label: "Tolitoli" },
  { value: "tondano", label: "Tondano" },
  { value: "toraja", label: "Toraja" },
  { value: "tual", label: "Tual" },
  { value: "tubaba", label: "Tulang Bawang Barat" },
  { value: "tuban", label: "Tuban" },
  { value: "tulungagung", label: "Tulungagung" },
  { value: "tumbang", label: "Tumbang" },
  { value: "ungaran", label: "Ungaran" },
  { value: "wakatobi", label: "Wakatobi" },
  { value: "wajo", label: "Wajo" },
  { value: "wakil", label: "Wakil" },
  { value: "walikota", label: "Walikota" },
  { value: "waingapu", label: "Waingapu" },
  { value: "wajo", label: "Wajo" },
  { value: "waropen", label: "Waropen" },
  { value: "watampone", label: "Watampone" },
  { value: "waykanan", label: "Way Kanan" },
  { value: "we", label: "We" },
  { value: "wotabula", label: "Wotabula" },
  { value: "yogyakarta", label: "Yogyakarta" },
  { value: "yuli", label: "Yuli" },
  { value: "yuliani", label: "Yuliani" },
];
